name: Build and Publish

on:
  push:
    branches:
      - develop
      - master
      - main
      - 'feature/**'

  pull_request:
    branches:
      - develop
      - master
      - main
      - 'feature/**'

jobs:

  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Build image and push to GitHub Container Registry for master branch
        if: ${{ github.ref == 'ref/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/rlkvch/django-docker-example:master-${{ env.GITHUB_SHA_SHORT }}
          push: ${{ github.ref == 'refs/heads/master' }}
      - name: Build image and push to GitHub Container Registry for main branch
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/rlkvch/django-docker-example:main-${{ env.GITHUB_SHA_SHORT }}
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push to GitHub Container Registry for develop branch
        if: ${{ github.ref == 'ref/heads/develop' }} || ${{ github.ref == 'ref/heads/feature/' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/rlkvch/django-docker-example:develop-${{ env.GITHUB_SHA_SHORT }}
          push: ${{ github.ref == 'refs/heads/develop' }}

  deploy:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: build
    steps:

      - name: Test
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - run: |
          touch secrets
          cat $MY_SECRET > secrets
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets